tikanoja/ft_transcendence

docker-compose.yml
services/frontend/Dockerfile

Changed docker to mount frontend files instead of copying.

Docker site mount

---

docker-compose.yml
srcs/backend/pong/Dockerfile
srcs/backend/pong/app.py
srcs/backend/pong/commands.txt
srcs/backend/pong/requirements.txt
srcs/backend/pong/test.py
srcs/backend/transcendence/conf/requirements.txt
srcs/backend/transcendence/srcs/pong/admin.py
srcs/backend/transcendence/srcs/pong/apps.py
srcs/backend/transcendence/srcs/pong/consumers.py
srcs/backend/transcendence/srcs/pong/models.py
srcs/backend/transcendence/srcs/pong/tests.py
srcs/backend/transcendence/srcs/pong/urls.py
srcs/backend/transcendence/srcs/pong/views.py
srcs/backend/transcendence/srcs/templates/pong/3dgen.html
srcs/backend/transcendence/srcs/transcendence/routing.py
srcs/backend/transcendence/srcs/transcendence/urls.py
srcs/frontend/conf/nginx.conf
srcs/frontend/srcs/css/styles.css
srcs/frontend/srcs/index.html
srcs/frontend/srcs/js/index.js
srcs/frontend/srcs/js/pong.js
srcs/frontend/srcs/js/router.js
srcs/frontend/srcs/js/settings.js

This pull request is the primary steps of the Object-Orientated module:
- game logic container is in place.
- html renders through Django.
- server-side game logic renders on front end, pending tidy up of clunkiness.
- front-end API communications in place.

Pc 15 module primary pull request

---

srcs/backend/pong/app.py

tell me if anything does not work

all the sheriis requested changes should now be in the pong

---

srcs/backend/transcendence/srcs/app/forms.py
srcs/backend/transcendence/srcs/app/models.py
srcs/backend/transcendence/srcs/app/user.py
srcs/backend/transcendence/srcs/app/views.py
srcs/backend/transcendence/srcs/templates/user/friends.html
srcs/backend/transcendence/srcs/templates/user/play.html
srcs/backend/transcendence/srcs/transcendence/cors_middleware.py
srcs/frontend/srcs/js/index.js

Adds game invites. A simple form to choose game and send an invitation to a player.
User can cancel sen request. The invited user can accept/reject. Success prints on play.html for the current state (user in game or not).
Very similar to the friends system!
Minor updates:
- Fix to the middleware issue (Thanks Jenny!)
- Add GameInstance model (on which the game invitations are based on)

Pc 64 invite to game

---

srcs/backend/pong/app.py
srcs/backend/transcendence/srcs/templates/pong/pong.html
srcs/frontend/srcs/css/styles.css
srcs/frontend/srcs/js/pong.js

Pc 32 object oriented server side pong with cli

---

.gitignore
pong_cli.py
srcs/backend/pong/app.py
srcs/backend/transcendence/Dockerfile
srcs/backend/transcendence/conf/requirements.txt
srcs/backend/transcendence/srcs/app/user.py
srcs/backend/transcendence/srcs/pong/views.py
srcs/backend/transcendence/srcs/templates/pong/3dgen.html
srcs/frontend/srcs/js/pong.js

-connects the end of game state to django
-verifies the username

Pong django connection

---

srcs/frontend/srcs/css/styles.css
srcs/frontend/srcs/index.html
srcs/frontend/srcs/js/chat.js
srcs/frontend/srcs/js/index.js

- Added chat usernames linking to profiles as simple links for now, menu for invites etc would be perhaps nicer...
- Fixed element layout responsiveness a bit

PC 66 view profiles from chat

---

srcs/backend/transcendence/srcs/app/models.py
srcs/backend/transcendence/srcs/app/play.py
srcs/backend/transcendence/srcs/templates/user/play.html
srcs/backend/transcendence/srcs/templates/user/register.html
srcs/frontend/srcs/js/index.js

Guys I am so very tired of creating the same test accounts again and again!!!!
This one adds a dummy account creation button to register.html and js to automate creation for 10 test users.
Also tournament things still in progress coming in with the same merge.

Automate test account creation

---

srcs/backend/transcendence/srcs/app/play.py
srcs/backend/transcendence/srcs/app/user/account.py
srcs/backend/transcendence/srcs/app/user/dashboard.py
srcs/backend/transcendence/srcs/templates/user/play.html

Hello almost there!
- Fixes bracket not advancing when user deletes account in active tournament
- Prevents blocked users from inviting you to a tournament
- Joining a tournament will cancel the pending one if you are currently hosting a tournament
- Fixes tournament not advancing when there are overlapping tournament and normal games between two users

Pc 16 game tournament

---

srcs/backend/transcendence/srcs/app/forms.py
srcs/backend/transcendence/srcs/app/models.py
srcs/backend/transcendence/srcs/app/play.py
srcs/backend/transcendence/srcs/app/user/account.py
srcs/backend/transcendence/srcs/app/user/dashboard.py
srcs/backend/transcendence/srcs/app/user/session.py
srcs/backend/transcendence/srcs/app/views.py
srcs/backend/transcendence/srcs/pong/utils.py
srcs/backend/transcendence/srcs/templates/base.html
srcs/backend/transcendence/srcs/templates/partials/navbar_empty.html
srcs/backend/transcendence/srcs/templates/partials/navbar_full.html
srcs/backend/transcendence/srcs/templates/user/login.html
srcs/backend/transcendence/srcs/templates/user/play.html
srcs/backend/transcendence/srcs/templates/user/profile.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/delete_account.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/friends.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/game_history.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/manage_account.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/stats.html
srcs/backend/transcendence/srcs/templates/user/register.html
srcs/frontend/srcs/css/bootstrap-breakpoint.css
srcs/frontend/srcs/css/styles.css
srcs/frontend/srcs/index.html
srcs/frontend/srcs/js/router.js

This is a PR for the application of basic bootstrap styling of the project (not including the gameplay screen). **note:  the work for this PR was done on PC-20-bootstrap, this branch was made to properly rebased and create the PR**
- New fonts were added and can be found in the styles.css file
- forms were standardized which included modifying the Django form classes
- The navbar was moved from the index to be rendered with the various templates from the backend

Bootstrap rebased

---

srcs/backend/transcendence/srcs/app/forms.py
srcs/backend/transcendence/srcs/app/urls.py
srcs/backend/transcendence/srcs/app/user/account.py
srcs/backend/transcendence/srcs/app/user/profile.py
srcs/backend/transcendence/srcs/app/views.py
srcs/backend/transcendence/srcs/templates/user/profile.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/delete_account.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/manage_account.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/profile_picture.html
srcs/frontend/srcs/js/index.js

This PR fixes some issues found for the profiles:
- login_required decorator added to ensure correct routing for profiles and to respect session timeouts
- forms accepting blank inputs for email and using old variable names fixed
- error formatting changed for account management to be more specific to the action taken and not just appear potentially out of view of the user while scrolling the site.
-- profile picture is updated when new one is uploaded

Pc 90 profile routing and small fixes for accounts

---

srcs/backend/transcendence/srcs/app/user/session.py
srcs/backend/transcendence/srcs/pong/views.py
srcs/backend/transcendence/srcs/templates/pong/nogame.html
srcs/backend/transcendence/srcs/templates/user/logged_in.html
srcs/backend/transcendence/srcs/transcendence/cors_middleware.py
srcs/frontend/srcs/js/index.js
srcs/frontend/srcs/js/router.js

Hopefully the last branch called routing fix.
Fixes users going back in browser history while playing a game. (Updated URL for frontend on game canvas) Users navigating back to login while authenticated also handled in a similar way. (An error screen)

Pc 93 routing fix

---

srcs/backend/transcendence/srcs/app/user/profile.py
srcs/backend/transcendence/srcs/app/views.py
srcs/backend/transcendence/srcs/pong/urls.py
srcs/backend/transcendence/srcs/pong/views.py
srcs/backend/transcendence/srcs/templates/404.html
srcs/backend/transcendence/srcs/templates/user/404.html
srcs/backend/transcendence/srcs/templates/user/login.html
srcs/backend/transcendence/srcs/templates/user/profile.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/friends.html
srcs/backend/transcendence/srcs/templates/user/register.html
srcs/frontend/srcs/index.html

The PR updates the error page styling, fixed error returns for the pong app and non-existing profiles. I also changed to use the webfont for the bootstrap icons to make the html more readable.

Pc 92 update error page

---

srcs/backend/transcendence/srcs/app/user/account.py
srcs/backend/transcendence/srcs/templates/404.html
srcs/backend/transcendence/srcs/templates/pong/nogame.html
srcs/backend/transcendence/srcs/templates/user/account_deleted.html
srcs/backend/transcendence/srcs/templates/user/logged_in.html
srcs/frontend/srcs/index.html
srcs/frontend/srcs/js/index.js

This PR adds some user flow adjustments:
- Added button for no_game.html, logged_in.html
- Added a new page for accounts deleted with nav buttons for registering or logging in

Pc 97 buttons for error pages

---

srcs/frontend/srcs/js/colorwar.js
srcs/frontend/srcs/js/pong.js

- check scores- I am no longer able to trigger the endless game scenario
- remove tie from pong have kept it in colorwar as it is theoretically possible but over 8 games played while actively trying to tie and i cannot make it happen 
- check colorwar responsiveness and fixed this behavior:
press back arrow ‘render game’ and click play game renders but the color buttons are unresponsive
- 2d paddles are now visible on all screen sizes 
-tidied up some of the code, console.logs etc

minor fixes

---

srcs/backend/transcendence/srcs/app/user/account.py
srcs/backend/transcendence/srcs/app/user/dashboard.py
srcs/backend/transcendence/srcs/app/user/session.py
srcs/backend/transcendence/srcs/app/views.py
srcs/backend/transcendence/srcs/pong/utils.py
srcs/backend/transcendence/srcs/pong/views.py
srcs/backend/transcendence/srcs/templates/user/profile_partials/game_history.html
srcs/backend/transcendence/srcs/templates/user/profile_partials/stats.html

This PR:
- adds try/except blocks for views to catch any errors
- ensures json responses return status codes
- added functionality to the validate_match endpoint for games
- fixed the dashboard info for Color War games

Pc 99 error handing and http codes

---

Makefile
pong_cli/setup_cli.sh

Hello!
A simple little script to create pong_cli venv and install dependencies. (And a Makefile rule to go with it)

add script to automate cli setup and Makefile rule

---

srcs/backend/transcendence/srcs/app/user/account.py

Fixes the internal server on pw change! It was caused by looking for "password" instead of "new_password" heh!

fix pw change 500 error

---

srcs/backend/transcendence/srcs/app/play.py
srcs/backend/transcendence/srcs/transcendence/settings.py

- Fixes situation where user is trying to cancel participation in an active tournament
- Changed Django to debug=False !!!

Django debug=False, add participant cancel check

---

srcs/backend/transcendence/srcs/app/play.py
srcs/backend/transcendence/srcs/templates/user/play.html

-Fixes a bug where successive tournaments with same creator showed history in bracket
-Enhanced tournament creation wording

Pc 105 double tournament fix

---

srcs/backend/database/Dockerfile
srcs/backend/transcendence/Dockerfile
srcs/backend/transcendence/srcs/app/models.py
srcs/backend/transcendence/srcs/app/play.py
srcs/backend/transcendence/srcs/app/urls.py
srcs/backend/transcendence/srcs/app/user/dashboard.py
srcs/backend/transcendence/srcs/app/user/relations.py
srcs/backend/transcendence/srcs/templates/user/register.html
srcs/backend/transcendence/srcs/transcendence/settings.py

- Comments out automatic user creation
- Cleans up comments and logger prints
- Removed c1r5p9 from allowed hosts

tidying up
